//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibby.Bot.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bibby.Bot.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;Text&quot;: &quot;Übersetzung&quot;
        ///	}
        ///].
        /// </summary>
        internal static string TranslationRequest {
            get {
                return ResourceManager.GetString("TranslationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;detectedLanguage&quot;: {
        ///            &quot;language&quot;: &quot;de&quot;,
        ///            &quot;score&quot;: 1
        ///        },
        ///        &quot;translations&quot;: [
        ///            {
        ///                &quot;text&quot;: &quot;Text for translation&quot;,
        ///                &quot;to&quot;: &quot;en&quot;
        ///            },
        ///            {
        ///                &quot;text&quot;: &quot;bIngDaq ghItlh leghlu&apos; mughmeH&quot;,
        ///                &quot;to&quot;: &quot;tlh&quot;
        ///            }
        ///        ]
        ///    }
        ///].
        /// </summary>
        internal static string TranslationResponse {
            get {
                return ResourceManager.GetString("TranslationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;error&quot;: {
        ///        &quot;code&quot;: 400005,
        ///        &quot;message&quot;: &quot;The field Text must be a string or array type with a minimum length of &apos;1&apos;.&quot;
        ///    }
        ///}.
        /// </summary>
        internal static string TranslationResponseError {
            get {
                return ResourceManager.GetString("TranslationResponseError", resourceCulture);
            }
        }
    }
}
